language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB_USER=root

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y language-pack-fr language-pack-fr-base
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer install --prefer-dist --dev
  - sh -c "mysql -u$DB_USER -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS thelia;SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - php Thelia thelia:install --db_host=localhost --db_username=$DB_USER --db_name=thelia
  - php setup/faker.php
  - php Thelia module:activate Colissimo
  - php Thelia module:activate Cheque
