language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB_USER=root

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y language-pack-fr language-pack-fr-base
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer install --prefer-dist --dev
  - sh -c "mysql -u$DB_USER -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS thelia;SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - php Thelia thelia:install --db_host=localhost --db_username=$DB_USER --db_name=thelia
  - php setup/faker.php
  - php Thelia module:refresh
  - php Thelia module:activate Colissimo
  - php Thelia module:activate Cheque
  - php Thelia module:activate HookTest
  - php Thelia module:activate VirtualProductDelivery
  - php Thelia admin:create --login_name thelia2 --password thelia2 --last_name thelia2 --first_name thelia2
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - php -S localhost:8000 -t web/ >/dev/null 2>&1 &
  - sleep 3
  - cd ..
  - git clone https://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.1-beta3
  - cd ../thelia

script: "./run-tests.sh"
